export const baseSkills = {
	"Accounting": 5,
	"Animal Handling": 5,
	"Anthropology": 1,
	"Appraise": 5,
	"Archaeology": 1,
	"Art/Craft (Acting)": 5,
	"Art/Craft": 5,
	"Art/Craft (Fine Art)": 5,
	"Art/Craft (Forgery)": 5,
	"Art/Craft (Photography)": 5,
	"Charm": 15,
	"Civics": 10,
	"Climb": 20,
	"Computer Use": 5,
	"Credit Rating": 0,
	"Cthulhu Mythos": 0,
	"Demolitions": 1,
	"Disguise": 5,
	"Diving": 1,
	"Dodge": 0,
	"Drive Auto": 20,
	"Drive Carriage": 20,
	"Drive Horse / Oxen": 20,
	"Drive Wagon / Coach": 20,
	"Electrical Repair": 10,
	"Electronics": 1,
	"Empire": 25,
	"Fast Talk": 5,
	"Fighting": 0,
	"Fighting (Axe)": 15,
	"Fighting (Brawl)": 25,
	"Fighting (Chainsaw)": 10,
	"Fighting (Flail)": 10,
	"Fighting (Garrote)": 15,
	"Fighting (Spear)": 20,
	"Fighting (Sword)": 20,
	"Fighting (Throw)": 20,
	"Fighting (Whip)": 5,
	"Firearms (Any)": 0,
	"Firearms (Artillery)": 1,
	"Firearms (Bow)": 15,
	"Firearms (Flamethrower)": 10,
	"Firearms (Handgun)": 20,
	"Firearms (Heavy Weapons)": 10,
	"Firearms (Machine Gun)": 10,
	"Firearms (Rifle/Shotgun)": 25,
	"Firearms (Submachine Gun)": 15,
	"First Aid": 30,
	"Gambling": 10,
	"History": 5,
	"Hypnosis": 1,
	"Intimidate": 15,
	"Jump": 20,
	"Language": 1,
	"Language (Own)": 0,
	"Law": 5,
	"Library Use": 20,
	"Listen": 20,
	"Locksmith": 1,
	"Lore": 1,
	"Mechanical Repair": 10,
	"Medicine": 1,
	"Natural World": 10,
	"Navigate": 10,
	"Occult": 5,
	"Operate Heavy Machinery": 1,
	"Persuade": 10,
	"Pilot": 1,
	"Psychoanalysis": 1,
	"Psychology": 10,
	"Read Lips": 1,
	"Ride": 5,
	"Rope Use": 5,
	"Science": 1,
	"Science (Astronomy)": 1,
	"Science (Biology)": 1,
	"Science (Botany)": 1,
	"Science (Chemistry)": 1,
	"Science (Cryptography)": 1,
	"Science (Engineering)": 1,
	"Science (Forensics)": 1,
	"Science (Geology)": 1,
	"Science (Mathematics)": 10,
	"Science (Meteorology)": 1,
	"Science (Pharmacy)": 1,
	"Science (Physics)": 1,
	"Science (Zoology)": 1,
	"Sleight of Hand": 10,
	"Spot Hidden": 25,
	"Stealth": 20,
	"Survival": 10,
	"Swim": 20,
	"Track": 10,
	"Trap": 10
};